name: Tag on PR Merger

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

env:
  TAG_PREFIX: 'v'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Create semantic tag
      env:
        TAG_NAME: ${{ env.TAG_PREFIX }}1.0.${{ github.run_number }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a $TAG_NAME -m "Release from PR #${{ github.event.pull_request.number }}"
        git push origin $TAG_NAME
